### ISSUE TITLE
PHP - some embedded html tags not matching

### ISSUE THREAD

**Issue by spchaplin** [vincaslt/vscode-highlight-matching-tag#18]
Thank you for your work on this extension!

I've found that some HTML tags embedded in PHP will not show as a match, while others do.  For example, in the following PHP snippet from Generate Press theme, I get no match on the first occurring <section> and <main> tags.  I inserted <section></section> towards the end as a test, and I do get a match on this final pair.
-----------------------------
<?php
/**
 * The template for displaying Archive pages.
 *
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package GeneratePress
 */
 
// No direct access, please
if (! defined('ABSPATH')) {
    exit;
}

get_header(); ?>
    <section id="primary" <?php generate_content_class(); ?>>
        <main id="main" <?php generate_main_class(); ?>>
            <?php do_action('generate_before_main_content'); ?>
<?php if (have_posts()) : ?>

            <?php do_action('generate_archive_title'); ?>

            <?php /* Start the Loop */ ?>
            <?php while (have_posts()) :
                the_post(); ?>

            <?php
                    /* Include the Post-Format-specific template for the content.
                     * If you want to override this in a child theme, then include a file
                     * called content-___.php (where ___ is the Post Format name) and that will be used instead.
                     */
                    get_template_part('content', get_post_format());
                ?>

                <?php endwhile; ?>

                <?php generate_content_nav('nav-below'); ?>

                <?php else : ?>

                <?php get_template_part('no-results', 'archive'); ?>

                <?php endif; ?>
                <?php do_action('generate_after_main_content'); ?>
        </main>
        
        <section></section>
    </section>
    

    <?php
    do_action('generate_sidebars');
    get_footer();
------------------------------------------------

When there is no match generated as it should, I sometimes get this console error:
----------------------------------------------------
[vincaslt.highlight-matching-tag] Cannot read property 'closing' of null: TypeError: Cannot read property 'closing' of null
	at findClosingTag (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:44:12)
	at findOpeningTagByPosition (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:74:35)
	at findOpeningTagByPosition (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:78:20)
	at findOpeningTag (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:82:12)
	at findCurrentTag (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:90:11)
	at vscode.window.onDidChangeTextEditorSelection (C:\Users\Name\.vscode\extensions\vincaslt.highlight-matching-tag-0.4.4\out\src\extension.js:134:28)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
	at e.$acceptSelectionsChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:416364)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:444633)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290278)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:289305
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:291224
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:58570
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853
-------------------------
Thanks for your help!

**Comment by adarshmadrecha** [comment]
The plugin working fine
![hilighting1](https://user-images.githubusercontent.com/11911938/33118300-612b6730-cf91-11e7-8516-8fb3194a2975.JPG)

Plugin not working
![hilighting2](https://user-images.githubusercontent.com/11911938/33118298-60dcd61a-cf91-11e7-8ca4-a3cf433d1410.JPG)
