### ISSUE TITLE
Invalid argument: Error: Invalid argument

### ISSUE THREAD

**Issue by kurtextrem** [vincaslt/vscode-highlight-matching-tag#4]
`Invalid argument: Error: Invalid argument
    at t._validatePosition (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:230616)
    at t._offsetAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:229960)
    at Object.offsetAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:228329)
    at getTextAfter (C:\Users\admin\.vscode-insiders\extensions\vincaslt.highlight-matching-tag-0.3.0\out\src\extension.js:5:60)
    at getClosingTag (C:\Users\admin\.vscode-insiders\extensions\vincaslt.highlight-matching-tag-0.3.0\out\src\extension.js:48:27)
    at findClosingTag (C:\Users\admin\.vscode-insiders\extensions\vincaslt.highlight-matching-tag-0.3.0\out\src\extension.js:67:46)
    at findCurrentTag (C:\Users\admin\.vscode-insiders\extensions\vincaslt.highlight-matching-tag-0.3.0\out\src\extension.js:87:16)
    at vscode.window.onDidChangeTextEditorSelection (C:\Users\admin\.vscode-insiders\extensions\vincaslt.highlight-matching-tag-0.3.0\out\src\extension.js:132:49)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30930)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34737)
    at t.$acceptSelectionsChanged (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:347776)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266430)
    at s (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154933)
    at h (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155610)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by vincaslt** [comment]
Could you provide a little bit of context? Where and when do you get this error?

**Comment by kurtextrem** [comment]
Got it in a JSX file. I can't give you the code that triggered anymore, but probably some invalid / incomplete tags while I was coding.

**Comment by vincaslt** [comment]
Ok, jsx can have some problems, as it mixes with javascript, and js inline compare messes up the tag resolution. I will look into this whenever I have some time. Did this crash vsode? And where did you see this error, in console?

**Comment by kurtextrem** [comment]
No, didn't crash - didn't notice any drawbacks. Just stumbled over the error when I've opened the Code dev tools.

**Comment by exdeniz** [comment]
I too this error:
```
Invalid argument: Error: Invalid argument
    at t._validatePosition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:230610)
    at t._offsetAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:229954)
    at Object.offsetAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:228323)
    at getTextAfter (/Users/exdeniz/.vscode/extensions/vincaslt.highlight-matching-tag-0.3.0/out/src/extension.js:5:60)
    at getClosingTag (/Users/exdeniz/.vscode/extensions/vincaslt.highlight-matching-tag-0.3.0/out/src/extension.js:48:27)
    at findClosingTag (/Users/exdeniz/.vscode/extensions/vincaslt.highlight-matching-tag-0.3.0/out/src/extension.js:67:46)
    at findCurrentTag (/Users/exdeniz/.vscode/extensions/vincaslt.highlight-matching-tag-0.3.0/out/src/extension.js:87:16)
    at vscode.window.onDidChangeTextEditorSelection (/Users/exdeniz/.vscode/extensions/vincaslt.highlight-matching-tag-0.3.0/out/src/extension.js:132:49)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptSelectionsChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:347799)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266424)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154927)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155604)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by vincaslt** [comment]
v0.5 fixed many problems and potentially this one, so closing it. Reopen it if this persists.
